### ISSUE TITLE
shopackify init -r does not create layout folder

### ISSUE THREAD

**Issue by azamanaza** [raylway/mango#8]
After
```
$ shopackify init -r
$ shopackify build
```

Error, no layout folder in `./shop/src`

**Comment by azamanaza** [comment]
For further investigation, code seems to be in place.

**Comment by zacariec** [comment]
Still happening even as of release v2.1.0 will need to take a further look.

**Comment by zacariec** [comment]
Patched in v2.1.1 - layout directory wasn't being created in the createDevDir function.
